### ISSUE TITLE
Datapoints overflow 

### ISSUE THREAD

**Issue by floskel** [tonsser/Cirque#3]
When adding dataPoints that sum to > 1.0 you get:
<img width="299" alt="screen shot 2017-02-06 at 10 22 42" src="https://cloud.githubusercontent.com/assets/1681866/22641260/3736a3be-ec56-11e6-83f7-f6e091d023f5.png">

This example is achieved with:
```cirque.dataPoints = [RankingGroup.match(value: 0.3), RankingGroup.achievements(value: 0.2), RankingGroup.votes(value: 0.7)]```

**Comment by floskel** [comment]
Not sure what the correct behaviour would look like. Maybe stop at 1.0

**Comment by philipengberg** [comment]
For now this will be considered a feature, until someone requests that.
